version: "3.1"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SERVERURL=${VPN_SERVER_URL}
      - SERVERPORT=51820 
      - PEERS=openwrt
      - ALLOWEDIPS=192.168.49.0/24, 10.13.13.0/24
      - LOG_CONFS=false
    volumes:
      - ${VPN_CONFIG_DIR}:/config
      - /lib/modules:/lib/modules 
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.forwarding=1
    networks: 
      nw:
        ipv4_address: 192.168.49.10
    restart: unless-stopped

  omada:
    container_name: omada
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=80
      - MANAGE_HTTPS_PORT=443
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/Los_Angeles
    command: [
            "/usr/bin/java",
            "-server",
            "-Xms256m",
            "-Xmx640m",
            "-XX:MaxHeapFreeRatio=60",
            "-XX:MinHeapFreeRatio=30",
            "-XX:+HeapDumpOnOutOfMemoryError",
            "-XX:HeapDumpPath=/opt/tplink/EAPController/logs/java_heapdump.hprof",
            "-Djava.awt.headless=true",
            "-cp",
            "/opt/tplink/EAPController/lib/*::/opt/tplink/EAPController/properties:",
            "com.tplink.smb.omada.starter.OmadaLinuxMain"
        ]
    networks:
      nw:
        ipv4_address: 192.168.49.2
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
      - cert:/cert

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks: 
      nw:
        ipv4_address: 192.168.49.11

  sftp:
    container_name: sftpgo
    image: drakkan/sftpgo:alpine-slim
    restart: unless-stopped
    networks: 
      nw:
        ipv4_address: 192.168.49.12
    volumes:
      - sftp-home:/var/lib/sftpgo
      - sftp-data:/srv/sftpgo

networks:
  nw:
    ipam:
      config:
        - subnet: "192.168.49.0/24"


volumes:
  omada-data:
  omada-logs:
  tsstate:
  cert:
  sftp-home:
  sftp-data:

